use a modern release action

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -13,46 +13,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v3
 
       - name: Build Debian Package
-        run: dpkg-deb --build nopasswd
+        run: dpkg-deb --root-owner-group --build nopasswd
 
-      - name: Rename Debian Package
+      - name: Verify Version
+        if: startsWith(github.ref, 'refs/tags/v')
+        id: check_version
+        run: |
+          version=$(dpkg-deb --field nopasswd.deb Version)
+          if [[ ! "${{ github.ref }}" == "ref/tag/v${version}" ]]; then
+            echo "Error: Package version ($version) does not match tag version ($tag_version)"
+            exit 1
+          fi
+          echo "::set-output name=version::$version"
+
+      - name: Rename Package
         run: dpkg-name nopasswd.deb
 
-      - name: Determine Renamed Package Name
+      - name: Determine Package Name
         id: extract_filename
         run: echo "::set-output name=filename::$(find nopasswd_*)"
 
-      - name: Upload Built Package as Artifact
+      - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ${{ steps.extract_filename.outputs.filename }}
           path: ${{ steps.extract_filename.outputs.filename }}
 
-      - name: Create Release
+      - name: Release
         if: startsWith(github.ref, 'refs/tags/v')
         id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        uses: softprops/action-gh-release@v2
         with:
-          tag_name: ${{ github.ref }}
-          release_name: Release ${{ steps.check_version.outputs.version }}
+          files: ${{ steps.extract_filename.outputs.filename }} 
           draft: true
-          prerelease: false
-
-      - name: Upload Release Asset
-        if: startsWith(github.ref, 'refs/tags/v')
-        id: upload_release_asset
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ steps.extract_filename.outputs.filename }}
-          asset_name: ${{ steps.extract_filename.outputs.filename }}
-          asset_content_type: application/octet-stream
 
